// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Generates descriptions of handcrafted jewelry artistry and emotional storytelling.
 *
 * - generateJewelleryDescription - A function that generates jewelry descriptions.
 * - GenerateJewelleryDescriptionInput - The input type for the generateJewelleryDescription function.
 * - GenerateJewelleryDescriptionOutput - The return type for the generateJewelleryDescription function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateJewelleryDescriptionInputSchema = z.object({
  jewelleryType: z.string().describe('The type of jewellery (e.g., necklace, earrings, ring).'),
  material: z.string().describe('The material the jewellery is made of (e.g., gold, silver, diamonds).'),
  craftsmanshipDetails: z.string().describe('Details about the craftsmanship involved in creating the jewellery.'),
  storyInspiration: z.string().describe('The story or inspiration behind the jewellery design.'),
});
export type GenerateJewelleryDescriptionInput = z.infer<typeof GenerateJewelleryDescriptionInputSchema>;

const GenerateJewelleryDescriptionOutputSchema = z.object({
  description: z.string().describe('A detailed description of the jewellery, including its artistry and the story it tells.'),
});
export type GenerateJewelleryDescriptionOutput = z.infer<typeof GenerateJewelleryDescriptionOutputSchema>;

export async function generateJewelleryDescription(
  input: GenerateJewelleryDescriptionInput
): Promise<GenerateJewelleryDescriptionOutput> {
  return generateJewelleryDescriptionFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateJewelleryDescriptionPrompt',
  input: {schema: GenerateJewelleryDescriptionInputSchema},
  output: {schema: GenerateJewelleryDescriptionOutputSchema},
  prompt: `You are a master storyteller, skilled in describing the artistry and emotional significance of handcrafted jewellery.

  Given the following information, craft a compelling and engaging description that highlights the unique value and craftsmanship of the jewellery.

  Jewellery Type: {{{jewelleryType}}}
  Material: {{{material}}}
  Craftsmanship Details: {{{craftsmanshipDetails}}}
  Story Inspiration: {{{storyInspiration}}}

  Description:`,
});

const generateJewelleryDescriptionFlow = ai.defineFlow(
  {
    name: 'generateJewelleryDescriptionFlow',
    inputSchema: GenerateJewelleryDescriptionInputSchema,
    outputSchema: GenerateJewelleryDescriptionOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
